return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.7.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 3,
  nextobjectid = 3,
  properties = {},
  tilesets = {
    {
      name = "tinySLATES [16x16px orthogonal tileset by Ivan Voirol]",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tinySLATES [16x16px orthogonal tileset by Ivan Voirol].png",
      imagewidth = 512,
      imageheight = 512,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 1,
      name = "Tile Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      data = "yQAAAAwBAADKAAAAyQAAAAkBAACrAAAACwEAAMkAAACpAAAA7AAAAMwAAAAMAQAACwEAAOwAAAALAQAAyQAAAKoAAADrAAAA6gAAAAsBAAALAQAA7AAAAAsBAADJAAAA7AAAAAoBAACrAAAArAAAAMwAAADqAAAADAEAAKoAAAAMAQAA6gAAAKsAAADMAAAAzAAAAAwBAADMAAAAywAAAOoAAACrAAAA6wAAAAkBAADJAAAArAAAAMsAAADsAAAAywAAAOoAAADJAAAArAAAAKoAAAAKAQAA6wAAAMwAAAAKAQAA6QAAAAwBAADrAAAACQEAAOsAAADMAAAA6QAAAOsAAACqAAAAywAAAKsAAACqAAAA6gAAAKwAAAALAQAACwEAAOoAAACqAAAACgEAAOkAAADpAAAAywAAAAkBAACpAAAAzAAAAOsAAADsAAAACgEAAOoAAADrAAAA6gAAAKsAAACpAAAACgEAAAsBAAAJAQAACQEAAKoAAADrAAAAqQAAAAwBAACrAAAA6wAAAOwAAADKAAAAqQAAAMwAAAALAQAAyQAAAKoAAADqAAAAygAAAKoAAAALAQAAzAAAAKsAAADrAAAADAEAAAsBAADMAAAA6gAAAMwAAADMAAAA6QAAAMwAAAAKAQAAyQAAAMwAAACrAAAA6gAAAKwAAAAJAQAAywAAAOkAAACsAAAACgEAAOsAAAAKAQAAqgAAAAkBAAAKAQAACwEAAOkAAACrAAAAyQAAAOkAAADrAAAA6gAAAOoAAAAKAQAA6gAAAOoAAADsAAAA6gAAAAoBAACrAAAA6QAAAMwAAADpAAAACQEAAOkAAADKAAAAyQAAAAkBAADLAAAA6wAAAKoAAADJAAAACgEAAKsAAACpAAAAqwAAAAkBAADJAAAA6gAAAOwAAAAMAQAAywAAAMwAAAALAQAArAAAAOkAAADqAAAAqwAAAAwBAACrAAAArAAAAAsBAACsAAAAqgAAAMsAAAAMAQAAqwAAAKoAAAAMAQAAyQAAAAsBAAALAQAA6wAAAOkAAADsAAAAyQAAAMwAAADJAAAAqQAAAMkAAACrAAAAywAAAKkAAADLAAAACQEAAMwAAAAMAQAAqwAAAAoBAADJAAAA6wAAAAkBAADKAAAArAAAAAwBAADpAAAA6gAAAKwAAACpAAAAqwAAAOoAAADJAAAA6gAAAAkBAAAJAQAA6gAAAOoAAAAJAQAACgEAAOwAAAAMAQAACQEAAOoAAAAMAQAAqgAAAAsBAACqAAAACQEAAAoBAADqAAAA7AAAAAoBAADMAAAA7AAAAMsAAADMAAAACQEAAKkAAADsAAAAzAAAAMoAAACqAAAACQEAAAoBAAALAQAArAAAAAkBAACsAAAArAAAAMkAAADKAAAArAAAAKoAAACrAAAAywAAAAoBAADKAAAArAAAAAkBAACpAAAA7AAAAAkBAAAJAQAA6wAAAOsAAACsAAAA7AAAAKoAAAAKAQAACwEAAMsAAAAJAQAAzAAAAAoBAAAMAQAAqQAAAOsAAADsAAAAqgAAAMsAAADKAAAAqQAAAKoAAADLAAAArAAAAOkAAAAJAQAAqwAAAAkBAAALAQAA6wAAAAwBAADsAAAADAEAAKkAAADpAAAAqgAAAMsAAACsAAAA6gAAAMkAAADsAAAAqwAAAAwBAAAMAQAAzAAAAAsBAADJAAAAqgAAAOoAAADrAAAAqwAAAOsAAACrAAAAqgAAAKkAAAAMAQAACgEAAKwAAACpAAAAywAAAMkAAACpAAAA6gAAAMsAAACrAAAACgEAAMkAAADJAAAA6gAAAAoBAADsAAAArAAAAAsBAADMAAAAygAAAOkAAADJAAAAygAAAOoAAAAJAQAAqwAAAKkAAADsAAAAygAAAAoBAADJAAAACQEAAKoAAADqAAAArAAAAKoAAACsAAAACQEAAOwAAACrAAAAqgAAAMkAAADrAAAA6QAAAAwBAADJAAAAqgAAAOoAAADrAAAAygAAAMwAAADKAAAACwEAAKsAAACpAAAADAEAAKkAAADrAAAACgEAAMwAAADsAAAAyQAAAKsAAADrAAAArAAAAMkAAADJAAAAqgAAAAoBAACsAAAAyQAAAOoAAACqAAAAywAAAKsAAADKAAAACgEAAKkAAACpAAAA6gAAAAoBAACsAAAA7AAAAOwAAAAJAQAAygAAAAsBAACqAAAAzAAAAMwAAADKAAAAqgAAAKkAAACpAAAA6wAAAMkAAADJAAAACgEAAAsBAADLAAAACQEAAAoBAACsAAAA6QAAAKwAAADMAAAAzAAAAKkAAADJAAAACgEAAAoBAADLAAAAqwAAAOwAAADqAAAA6wAAAAsBAACqAAAA6QAAAOkAAACqAAAAzAAAAKwAAACrAAAAyQAAAOkAAADLAAAA7AAAAMsAAACpAAAA6QAAAMoAAADMAAAACQEAAMsAAACpAAAA6QAAAKoAAACsAAAAywAAAOsAAAAKAQAAzAAAAKoAAACsAAAA6QAAAKoAAAAKAQAA6wAAAOoAAAALAQAACgEAAMwAAADrAAAACQEAAMkAAAAKAQAACwEAAOsAAAAKAQAACQEAAKwAAADrAAAADAEAAKsAAADrAAAA7AAAAKsAAADsAAAAygAAAKwAAAALAQAArAAAAMwAAACrAAAACwEAAKsAAACqAAAADAEAAAwBAAALAQAACQEAAOkAAADLAAAArAAAAKsAAADqAAAACgEAAOoAAADLAAAAzAAAAMwAAADKAAAA6gAAAAsBAADpAAAAqQAAAAoBAACsAAAACwEAAAsBAADrAAAA6gAAAMkAAAAJAQAAygAAAKoAAAAMAQAAqQAAAAsBAADsAAAADAEAAKwAAAAMAQAAyQAAAMoAAACqAAAA6gAAAMoAAAAKAQAAyQAAAKoAAADLAAAADAEAAOkAAADpAAAAzAAAAMwAAADrAAAA7AAAAAwBAADKAAAA7AAAAAwBAACrAAAAzAAAAAwBAADKAAAA6QAAAKsAAACqAAAAqQAAAOsAAADKAAAACgEAAKsAAADpAAAAqgAAAAoBAACqAAAAqgAAAAoBAADsAAAAygAAAMsAAACrAAAAygAAAKoAAADJAAAAywAAAMkAAACsAAAAygAAAKoAAADqAAAAzAAAAMsAAACsAAAACQEAAOsAAACsAAAACQEAAAoBAAALAQAA6gAAAAsBAAALAQAAqQAAAKwAAACqAAAAyQAAAOkAAADqAAAACwEAAOsAAADKAAAACwEAAOkAAADJAAAA6QAAAKwAAADpAAAAzAAAAAsBAADpAAAA6wAAAMsAAAALAQAA6gAAAAwBAAAMAQAAqwAAAMwAAADpAAAAqgAAAAwBAAAJAQAA6QAAAOsAAAALAQAADAEAAMkAAADLAAAAyQAAAAoBAADLAAAArAAAAMsAAADMAAAAywAAAOwAAAAJAQAAzAAAAKsAAACpAAAACwEAAOsAAAAJAQAAygAAAKkAAAAKAQAA7AAAAAsBAADMAAAAywAAAOsAAADpAAAACgEAAKsAAAAKAQAA6gAAAAkBAADMAAAAqQAAAAoBAAAMAQAAzAAAAAwBAADpAAAADAEAAKkAAACpAAAA6QAAAKoAAAAKAQAAyQAAAAsBAAAJAQAAqgAAAAkBAAALAQAADAEAAOoAAADpAAAACwEAAOsAAACrAAAA6wAAAAkBAAAMAQAAywAAAMwAAAAJAQAACgEAAKsAAACsAAAACQEAAAsBAADrAAAAzAAAAMwAAADMAAAADAEAAAwBAAALAQAAqgAAAAsBAACqAAAA6wAAAOwAAADJAAAAzAAAAMwAAACsAAAAzAAAAKwAAACsAAAA7AAAAAsBAADMAAAACgEAAMoAAAAKAQAADAEAAAsBAADrAAAAqQAAAAsBAAAMAQAACwEAAKoAAADsAAAAqwAAAOoAAAALAQAACgEAAMwAAADKAAAArAAAAAsBAADLAAAArAAAAAkBAADqAAAAqQAAAKoAAACsAAAADAEAAAsBAADMAAAADAEAAOwAAAAMAQAA7AAAAOkAAAAMAQAAqQAAAAsBAADrAAAArAAAAOoAAACpAAAADAEAAAwBAAAMAQAAygAAAKkAAADJAAAA6gAAAKsAAADrAAAAqwAAAAsBAACpAAAAqgAAAOoAAADsAAAA6wAAAMsAAADJAAAADAEAAAoBAAAKAQAAygAAAMsAAADMAAAA6QAAAAsBAAAMAQAACQEAAMkAAACsAAAACgEAAMoAAAAJAQAAqwAAAMwAAACsAAAArAAAAOsAAADJAAAADAEAAMkAAACqAAAAzAAAAKkAAACpAAAA6gAAAMwAAADJAAAACgEAAOwAAACrAAAAyQAAAKwAAADsAAAACQEAAOoAAAAMAQAA6gAAAKwAAAAMAQAACQEAAAwBAADrAAAAqQAAAMkAAADqAAAArAAAAOsAAAAJAQAACQEAAAsBAACpAAAACQEAAOsAAADKAAAA6QAAAAkBAADMAAAA6gAAAKkAAADKAAAAzAAAAMoAAADJAAAArAAAAAoBAACsAAAACwEAAOkAAAALAQAArAAAAAsBAADpAAAACwEAAMkAAADLAAAArAAAAOoAAADLAAAAqgAAAKsAAACrAAAACQEAAKkAAAAJAQAA6QAAAOoAAADJAAAACQEAAAkBAAAKAQAACgEAAAsBAADKAAAA6gAAAKkAAADMAAAADAEAAOoAAACqAAAAyQAAAMoAAAAMAQAAzAAAAAsBAADsAAAAzAAAAMsAAADpAAAAyQAAAKwAAADqAAAACQEAAMsAAAAMAQAA6wAAAOoAAAAJAQAAqwAAAMoAAADsAAAArAAAAOkAAADMAAAAygAAAOsAAACqAAAAqQAAAKsAAADLAAAACwEAAKkAAACpAAAA6wAAAKsAAADLAAAA6wAAAAwBAAALAQAA7AAAAKsAAACpAAAAywAAAAoBAADLAAAAyQAAAMwAAADLAAAAqwAAAMoAAADKAAAAywAAAMoAAAAMAQAA6gAAAAoBAADJAAAAzAAAAMsAAADqAAAACQEAAOoAAADqAAAAqQAAAOsAAADqAAAA6wAAAOoAAADrAAAA7AAAAMoAAADLAAAADAEAAMwAAAAJAQAAqgAAAOoAAACpAAAA6wAAAAsBAAAKAQAArAAAAMwAAADJAAAAyQAAAOsAAADLAAAAygAAAMwAAADqAAAAqQAAAKsAAAAMAQAACQEAAOsAAAALAQAACQEAAAoBAADLAAAADAEAAOkAAAALAQAAqwAAAMoAAADLAAAAzAAAAOwAAADsAAAAqgAAAOsAAACqAAAAqwAAAAsBAADKAAAAygAAAOkAAAAJAQAA6gAAAOwAAACsAAAA6gAAAKkAAADJAAAAzAAAAAwBAAALAQAADAEAAAkBAACsAAAADAEAAOwAAACqAAAACgEAAA=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "doesnotmatter",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "humanReadableDoor",
          type = "",
          shape = "rectangle",
          x = 255.47,
          y = 157.205,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 855,
          visible = true,
          properties = {
            ["Constructor"] = "other_circle.constr",
            ["WhateverIsHereWillBeConstructorParams"] = "4"
          }
        }
      }
    }
  }
}
